spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/rainy?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: rootROOT@1234
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: root1234
  cloud:
    # 服务注册中心
    nacos:
      discovery:
        server-addr: 192.168.95.130:8848
        group: rainy-dev
        namespace: 910a91d6-39cc-4677-8ce9-d320846a36c7